repos:
  - repo: https://github.com/google/osv-scanner/
    rev: "2.0.0"
    hooks:
      - id: osv-scanner

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: "0.6.10"
    hooks:
      - id: uv-lock
      - id: uv-sync

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "0.11.2"
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/fsfe/reuse-tool
    rev: v5.0.2
    hooks:
      - id: reuse-lint-file
