repos:
  - repo: https://github.com/google/osv-scanner/
    rev: "v2.2.2"
    hooks:
      - id: osv-scanner

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/fsfe/reuse-tool
    rev: v5.0.2
    hooks:
      - id: reuse-lint-file

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: "0.8.13"
    hooks:
      - id: uv-lock
      - id: uv-sync

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.12.10"
    hooks:
      - id: ruff-check
      - id: ruff-format
