#--:schema https://www.schemastore.org/prek.json
minimum_prek_version = "0.3.4"

[[repos]]
repo = "https://github.com/google/osv-scanner/"
rev = "b56b5191101d5f27d4787d5583d8d01e9518a7af"  # frozen: v2.4.0

[[repos.hooks]]
id = "osv-scanner"
args = ["scan", "source", "--recursive", "."]

[[repos]]
repo = "https://github.com/gitleaks/gitleaks"
rev = "83d9cd684c87d95d656c1458ef04895a7f1cbd8e"  # frozen: v8.30.1
hooks = [{id = "gitleaks"}]

[[repos]]
repo = "https://codeberg.org/fsfe/reuse-tool"
rev = "a1bb792acda6fd0724936b4ebbdbc8eceb9c0459"  # frozen: v6.2.0
hooks = [{id = "reuse-lint-file"}]

[[repos]]
repo = "https://github.com/astral-sh/uv-pre-commit"
rev = "d9fca3320346514799461a80b0753eb45d707d46"  # frozen: 0.11.28
hooks = [{id = "uv-lock"}, {id = "uv-sync"}]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "01a675ea018f2fb714478a5ffb83fcea8374bb06"  # frozen: v0.15.21
hooks = [{id = "ruff-check"}, {id = "ruff-format"}]
