minimum_prek_version: "0.3.0"

repos:
  - repo: builtin
    hooks:
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/fsfe/reuse-tool
    rev: v6.2.0
    hooks:
      - id: reuse-lint-file

  - repo: local
    hooks:
      # official hook uses docker, i prefer a local copy
      - id: shellcheck
        name: shell check
        entry: shellcheck
        language: system
        types: [shell]

      # there is no official shell format hook
      - id: shellformat
        name: shell format
        entry: shfmt --diff
        language: system
        types: [shell]
