version = 1

[[annotations]]
SPDX-FileCopyrightText = "Copyright © 2025 Pablo Castellazzi <pablo.castellazzi@icloud.com>"
SPDX-License-Identifier = "MIT"
precedence = "override"

path = [
  ".editorconfig",
  ".gitignore",
  ".pre-commit-config.yaml",
  ".prekignore",
  "GNUmakefile",
  "LICENSES/MIT.txt",
  "README.md",
  "REUSE.toml",
  "copier.yml",
  "macros.jinja",
  "post_generation.sh",
  "scripts/update-python-version.sh",
  "template/.coveragerc.jinja",
  "template/.editorconfig",
  "template/.gitignore",
  "template/.pre-commit-config.yaml",
  "template/.python-version.jinja",
  "template/GNUmakefile.jinja",
  "template/README.md.jinja",
  "template/REUSE.toml.jinja",
  "template/pyproject.toml.jinja",
  "template/ruff.toml.jinja",
  "template/src/{{ project_module }}/__about__.py",
  "template/src/{{ project_module }}/__init__.py",
  "template/tests/__init__.py",
  "template/tests/test_version.py.jinja",
  "template/{{ _copier_conf.answers_file }}.jinja",
]
